# Generated by Django 3.1.5 on 2021-04-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=200)),
                ('jib', models.CharField(max_length=13)),
                ('pib', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('lozinka1', models.CharField(max_length=30)),
                ('lozinka2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OblastiInteresovanja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KorisnickeOblastiInteresovanja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('korisnikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aukcija.korisnik')),
                ('oblastiinteresovanjaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aukcija.oblastiinteresovanja')),
            ],
        ),
    ]
