# Generated by Django 3.1.5 on 2021-04-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aukcija', '0002_aukcija_proizvodi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='lozinka1',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='lozinka2',
        ),
    ]
